### PR TITLE
Made style combination as easy as SCSS, and makes karax the most lightweight and efficient web frontend framework,including Web APP and SSR

### PR DESCRIPTION
**Pull request by gogolxdong**
SCSS:
```
#scss file, needs an additional compilation
.problems {
  text-align: center;
  img,
  span {
    display: block;
  }
  img {
    margin: 10px auto;
  }
}
# nim code
for p in problems:
    tdiv(class="problems"):
        img(src = imgagePrefix & "tick.png")
        span(): text p

```
vs
```
#pure nim
var problemStyle = "text-align:center;"
for p in problems:
     tdiv(style=problem):
          img(style=problem&"display:block;margin: 10px auto;",src = imagePrefix & "tick.png")
          span(style=problem&"display:block;"): text p

```
Implementation also enhances SSR. You can run either run `nim js --hints:off main.nim` get its performant VDOM features or run `nim cpp -r --hints:off main.nim` to get its SSR version of the current VDOM tree with 
```
template kxi*(): int = 0
template addEventHandler*(n: VNode; k: EventKind; action: string; kxi: int = 0) =
    n.setAttr($k, action)
```
```
import karax / [karaxdsl, vdom, vstyles]
template kxi*(): int = 0
template addEventHandler*(n: VNode; k: EventKind; action: string; kxi: int = 0) =
    n.setAttr($k, action)
var fullScreenStyle="width:100%; height:100%;"
let main: VNode = 
  buildHtml tdiv(id="main",style="width:100%; height:100%;", onclick="click(this)")#implement click in some js file
 #buildHtml tdiv(id="main",style=fullScreenStyle) 
echo main
```

### CODE REVIEW

**Comment by zedeus** [comment]
I don't think this adds anything, this:
```nim
buildHtml tdiv(id="main",style="color:blue; text-align:center")
```

Can be written like this:
```nim
buildHtml tdiv(id="main",style={color: "blue", textAlign: "center"})
```

While still being short and very readable. I'm not against this change but it seems unnecessary to me when Karax has special support for styles.

**Comment by gogolxdong** [comment]
It confirms to intuition of many web frontend developers, reduces additional learning overhead. Some styles has to be variant to avoid reserverd keyword float like cssFloat. 
It provides convinience when rewriting applications in Karax, copy & paste is efficient and error resistant.
Besides, it's the same purpose with your PR, we long for this for a while, and thanks to your PR inspiration to have me done this finally.

**Comment by dvska** [comment]
Hi Zed,

```     
     tdiv(onscroll=scrollEvent, style=style(
         (StyleAttr.height, cstring"400px"), (StyleAttr.overflow, cstring"scroll"))):
```

(from the scrollapp sample)

can it be rewritten somehow?

**Comment by zedeus** [comment]
@dvska sure

```nim
tdiv(onscroll=scrollEvent, style={height: "400px", overflow: "scroll"})
```

This works because the `{k: v}` construct in Nim creates tuples of tuples, so the above results in the same as the example given.

**Comment by gogolxdong** [comment]
I do 

> Why don't you make a separated README file in Chinese?

I do here , https://github.com/gogolxdong/karax

**Comment by kristianmandrup** [comment]
What is the status on this?

**Comment by xflywind** [comment]
I think it maybe a bit harder to use link css in karax native.But I can't find a reasonable solution.
Now, I can only think of a helper function to generate helper Html Once when the view function is used.
Code in https://github.com/planety/kview

**Pull request closed without merging**
