### PR TITLE
add transition events

### PR DESCRIPTION
**Pull request by bung87**
see https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent

### CODE REVIEW

**Comment by Araq** [comment]
Is this really a good idea? https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontransitioncancel says not all browsers support it. In fact, not even Chrome supports it?

**Comment by bung87** [comment]
> Is this really a good idea? https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontransitioncancel says not all browsers support it. In fact, not even Chrome supports it?
transition event family using `addEventListener` are full supported.

**Comment by bung87** [comment]
so remove `ontransitioncancel` is fine for now ? if so , I'll remove that one from this PR.

**Comment by Araq** [comment]
> ust because these are here doesn't mean they'll break anything if the browser doesn't support them, no?

I don't know. :-)

**Comment by Araq** [comment]
Does "silently fails" mean it produces an error on the internal console? Cause if so, that's most annoying during development (adds noise).

**Comment by bung87** [comment]
it just ignored. does nothing.

**Pull request merged**
