### PR TITLE
Introduce notion of karax instance

### PR DESCRIPTION
**Pull request by bluenote10**
After thinking about #9 a bit more, I think a proper solution would require to avoid having single/global state. The PR is only a draft how the design could look like to avoid global state, and introduce the notion of a Karax instance. 

This would allow to run multiple Karax instances, which can be useful for projects which want to migrate to Karax, but can't introduce on the top/root level. To start small, Karax could be introduced just in certain parts in the DOM.

Notes:
- I have only ported the scrollapp as an example.
- I did not pull the "focus" state into the Karax state, because it is inherently global.

What do you think about the idea?

### CODE REVIEW

**Comment by Araq** [comment]
> What do you think about the idea?

Right now, I like it very much. :-) A bigger example to tinker with is required though. However, the refactoring is still innocent enough, rebase?

**Comment by bluenote10** [comment]
I still have to figure out how this will impact the `component` macro. My problem is that I still don't fully understand how the components work. So far I feel like I can do everything without them. For instance in the mediaplayer example, making `mplayer` a component does not seem necessary?

**Comment by Araq** [comment]
The component macro needs to be rewritten anyway. :-)

**Comment by bluenote10** [comment]
Okay I have adjusted everything except for the `example.nim`, `oldwidgets.nim`, and `scrollapp.nim` files in `experiments`. Do you want me to migrate them as well, or are they about to be changed anyway with the component macro change?

I have also added a basic travis config. Currently it just checks whether the important stuff compiles. I have some ideas how we could turn this into some nice headless-browser testing.

**Comment by bluenote10** [comment]
FYI if you want to check Travis: https://travis-ci.org/bluenote10/karax/

**Comment by Araq** [comment]
I wrote this part differently so that simple programs stay simple, hope you still like it.

**Comment by bluenote10** [comment]
Yes, much appreciated, solution looks really nice.

**Pull request closed without merging**
